trigger:
  batch: true
  branches:
    include:
    - feature/*
    - release
    - prerelease
    - main

pr:
  branches:
    include:
    - feature/*
    - release
    - prerelease
    - main
  paths:
    exclude:
    - ./*.md

stages:
- template: azure-pipelines/build-all.yml
  parameters:
    isOfficial: false
    signType: test

- stage: Test_Linux_Stage
  displayName: Test Linux
  dependsOn: []
  jobs:
  - template: azure-pipelines/test-matrix.yml
    parameters:
      # Prefer the dotnet from the container.
      installDotNet: false
      installAdditionalLinuxDependencies: true
      pool:
        name: NetCore-Public
        demands: ImageOverride -equals 1es-ubuntu-2004-open
      container: mcr.microsoft.com/dotnet/sdk:6.0
      jobName: 'Test Linux (.NET 6)'
  - template: azure-pipelines/test-matrix.yml
    parameters:
      # Prefer the dotnet from the container.
      installDotNet: false
      installAdditionalLinuxDependencies: true
      pool:
        name: NetCore-Public
        demands: ImageOverride -equals 1es-ubuntu-2004-open
      container: mcr.microsoft.com/dotnet/sdk:7.0
      jobName: 'Test Linux (.NET 7)'
  - template: azure-pipelines/test-matrix.yml
    parameters:
      # Prefer the dotnet from the container.
      installDotNet: false
      installAdditionalLinuxDependencies: true
      pool:
        name: NetCore-Public
        demands: ImageOverride -equals 1es-ubuntu-2004-open
      container: mcr.microsoft.com/dotnet/sdk:8.0
      jobName: 'Test Linux (.NET 8)'

- stage: Test_Windows_Stage
  displayName: Test Windows
  dependsOn: []
  jobs:
  - template: azure-pipelines/test-matrix.yml
    parameters:
      installDotNet: true
      pool:
        name: NetCore-Public
        demands: ImageOverride -equals 1es-windows-2022-open
      jobName: 'Test Windows'

- stage: Test_MacOS_Stage
  displayName: Test MacOS
  dependsOn: []
  jobs:
  - template: azure-pipelines/test-matrix.yml
    parameters:
      installDotNet: true
      pool:
        name: Azure Pipelines
        vmImage: macOS-13
      jobName: 'Test MacOS'

- stage: Test_OmniSharp
  displayName: Test OmniSharp
  dependsOn: []
  jobs:
  - job: Test
    strategy:
      matrix:
        linux:
          demandsName: 1es-ubuntu-2004-open
        windows:
          demandsName: 1es-windows-2022-open
    pool:
      name: NetCore-Public
      demands: ImageOverride -equals $(demandsName)
    steps:
    - template: azure-pipelines/test-omnisharp.yml
