name: OmniSharp-VSCode Release CI

on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'

    - name: Install dependencies
      run: |
          npm ci
          npm i -g gulp

    - name: Build extension package
      run: gulp 'vsix:release:package:platform-specific'

    - name: Run release tests
      run: npm run test:release

    - name: Get package version
      run: node -e "console.log('VERSION=' + require('./package.json').version)" >> $GITHUB_ENV

    - name: Upload release build (darwin-arm64)
      id: upload-release-asset-darwin-arm64
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          ./csharp-${{ env.VERSION }}-darwin-arm64.vsix
          ./csharp-${{ env.VERSION }}-darwin-x64.vsix
          ./csharp-${{ env.VERSION }}-linux-arm64.vsix
          ./csharp-${{ env.VERSION }}-linux-x64.vsix
          ./csharp-${{ env.VERSION }}-alpine-arm64.vsix
          ./csharp-${{ env.VERSION }}-alpine-x64.vsix
          ./csharp-${{ env.VERSION }}-win32-arm64.vsix
          ./csharp-${{ env.VERSION }}-win32-ia32.vsix
          ./csharp-${{ env.VERSION }}-win32-x64.vsix
