name: Update CHANGELOG
on:
  workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Update version.json
        run: npx gulp updateChangelog
      - name: Create version update PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update ${{ github.ref_name }} CHANGELOG
          title: '[automated] Update ${{ github.ref_name }} CHANGELOG'
          branch: merge/update-${{ github.ref_name }}-changelog
