parameters:
  - name: pool
    type: object
  - name: containerName
    type: string
    default: ''
  - name: dotnetVersion
    type: string
  - name: installAdditionalLinuxDependencies
    type: boolean
    default: false
  - name: testVSCodeVersion
    type: string

jobs:
- job:
  strategy:
    matrix:
      UnitTests:
        npmCommand: test:unit
        integration: false
      CSharpIntegrationTests:
        npmCommand: test:integration:csharp
        integration: true
      DevKitTests:
        npmCommand: test:integration:devkit
        integration: true
      RazorTests:
        npmCommand: test:integration:razor
        integration: true
  pool: ${{ parameters.pool }}
  ${{ if parameters.containerName }}:
    container: ${{ parameters.containerName }}
  steps:
  - template: /azure-pipelines/test.yml@self
    parameters:
      dotnetVersion: ${{ parameters.dotnetVersion }}
      installAdditionalLinuxDependencies: ${{ parameters.installAdditionalLinuxDependencies }}
      npmCommand: $(npmCommand)
      testVSCodeVersion: ${{ parameters.testVSCodeVersion }}
      isIntegrationTest: ${{ eq(variables.integration, 'true') }}